### ISSUE TITLE
Path issues (possible)

### ISSUE THREAD

**Issue by pranjalpokharel7** [abhiyandhakal/nvim-config#5]
Replace paths like `/home/abhiyan/` with `~/` so that it can work when you're changing systems (say). I haven't used nvim yet but pretty sure the file path can cause some complications.

https://github.com/abhiyandhakal/nvim-config/blob/20001d14fa5e998be52f6358a4eab63dec0699b9/plugin/packer_compiled.lua#L80

**Comment by abhiyandhakal** [comment]
thanks! I'll change that

**Comment by abhiyandhakal** [comment]
actually... I can just gitignore packer_compiled.lua
